# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_phone', models.CharField(max_length=30)),
                ('to_phone', models.CharField(max_length=30)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
